name: Make

on:
  push:
    branches: [ "goo-blender-master" ]
  pull_request:
    branches: [ "goo-blender-master" ]

jobs:
  build:

    runs-on: arch-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 
      uses: actions/setup-python@v3
      with:
        python-version: '3.9' 
        cache: 'pip' 
        
    - name: Python3.9-dev
      run: sudo apt-get install python3-dev python3-pip python3-tk python3-lxml python3-six
      
    - name: LibZstd_Numac
      run: |
        sudo apt install -y libzstd-dev
        sudo apt install numactl
        
    - name: Packages
      run: |
	    sudo pacman -S base-devel git subversion cmake libepoxy libxi libxcursor libxrandr libxinerama libxxf86vm python wayland-protocols libxkbcommon libdecor
        sudo apt install build-essential git subversion cmake libx11-dev libxxf86vm-dev libxcursor-dev libxi-dev libxrandr-dev libxinerama-dev libegl-dev
        sudo apt install libwayland-dev wayland-protocols libxkbcommon-dev libdbus-1-dev linux-libc-dev
		
	- name: Clone_Master
      run: |	
		mkdir ~/blender-git
		cd ~/blender-git
		git clone https://git.blender.org/blender.git
		
	- name: Checkout
	  run: |
        mkdir ~/blender-git/lib
		cd ~/blender-git/lib
		svn checkout https://svn.blender.org/svnroot/bf-blender/trunk/lib/linux_centos7_x86_64
		
    - name: Install Requirements.txt   
      run: pip install -r requirements.txt
        
    - name: Update Sudo
      run: sudo apt update
      
    - name: Update
      run: make update 

    - name: Make
      run: make
	  
    - name: BuilD
      run: make BuilD
