name: Build_Bl

on:
  push:
    branches: [ "goo-blender-master" ]
  pull_request:
    branches: [ "goo-blender-master" ]

jobs:
  build:
    name: Build Gooe_Blender
    runs-on: ubuntu-latest
    container: node:14
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v2
      with:
          python-version: "3.6"
          
    - name: Set up testing environment
      run: pip install -r goo-blender-master/requirements.txt
      
    - name: Check Node Version
      run: node --version
    
    - name: Check addons
      run: git submodule update --init --recursive
            
    - name: Install dependencies
      run: make
      
    - name: Run check
      run: make check
      
    - name: Run build1
      run: make build1
