name: Make

on:
  push:
    branches: [ "goo-blender-master" ]
  pull_request:
    branches: [ "goo-blender-master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 
      uses: actions/setup-python@v3
      with:
        python-version: '3.9' 
        cache: 'pip' # caching pip dependencies
        
    - name: Install Requirements.txt   
      run: pip install -r requirements.txt

    - name: Update Sudo
      run: sudo apt update

    - name: Scripts
      run: |
        sudo apt-get install python3-dev
        sudo apt install numactl
        sudo apt install -y libzstd-dev

    - name: Essentials
      run: |
        sudo apt install build-essential git subversion cmake libx11-dev libxxf86vm-dev libxcursor-dev libxi-dev libxrandr-dev libxinerama-dev libegl-dev
        sudo apt install libwayland-dev wayland-protocols libxkbcommon-dev libdbus-1-dev linux-libc-dev
        
  #  - name: RKI__
     # run: |
    #    mkdir ~/blender-git
    #    cd ~/blender-git
    #    git clone https://git.blender.org/blender.git
        
    #- name: RKI_0
    #  run: |
      #  mkdir ~/blender-git/lib
      #  cd ~/blender-git/lib
      #  svn checkout https://svn.blender.org/svnroot/bf-blender/trunk/lib/linux_centos7_x86_64

    - name: Submodule
     # run: git submodule update --init --recursive #update sub modules
      run: git clone https://github.com/dillongoostudios/goo-engine.git --recursive

    - name: Update
      run: make update 
      
    #- name: Setup cmake
     # uses: jwlawson/actions-setup-cmake@v1.13
     # with:
      #  cmake-version: '3.16.x'
   # - name: Use cmake
   #   run: cmake --version
                   
    - name: Make
      run: make 
      
