name: Make

on:
  push:
    branches: [ "goo-blender-master" ]
  pull_request:
    branches: [ "goo-blender-master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 
      uses: actions/setup-python@v3
      with:
        python-version: '3.9' 
        cache: 'pip' # caching pip dependencies
        
    - name: Install Requirements.txt   
      run: pip install -r requirements.txt

    - name: Update Sudo
      run: sudo apt update

    - name: Numact1_ZSTD
      run: |
        sudo apt install numactl
        sudo apt install -y libzstd-dev

    - name: Essentials
      run: |
        sudo apt install build-essential git subversion cmake libx11-dev libxxf86vm-dev libxcursor-dev libxi-dev libxrandr-dev libxinerama-dev libegl-dev
        sudo apt install libwayland-dev wayland-protocols libxkbcommon-dev libdbus-1-dev linux-libc-dev

    - name: Submodule
      run: git submodule update --init --recursive #update sub modules

    - name: Update_Code
      run: make update 
      
    - name: Check
      run: make check
                    
    - name: Make
      run: make
      
    #- name: BuilD
    #  run: make BuilD
